In [2]:
print ('yo')

yo


In [4]:
import pandas as pd #work with data as tables
import numpy as np #use number matrices
import matplotlib.pyplot as plt
import tensorflow as tf

In [5]:
#Step 1 load data
dataframe = pd.read_csv('data (1).csv') #dataframe object
#removed the features we don't care about
dataframe = dataframe.drop(['index', 'price', 'sq_price'], axis=1)
#we only use the first 10 rows
dataframe = dataframe[0:10]
dataframe


area  bathrooms
0  2104.0        3.0
1  1600.0        3.0
2  2400.0        3.0
3  1416.0        2.0
4  3000.0        4.0
5  1985.0        4.0
6  1534.0        3.0
7  1427.0        3.0
8  1380.0        3.0
9  1494.0        3.0

In [7]:
#Step 2 - add labels
#1 is a good buy and 0 is a bad buy
dataframe.loc[:, ('y1')] = [1,1,1,0,0,1,0,1,1,1]
#y2 is a negation of y1, opposite
dataframe.loc[:, ('y2')] = dataframe['y1'] == 0
#turn TRUE/FALSE values to 1s and 0s
dataframe.loc[:, ('y2')] = dataframe['y2'].astype(int)
dataframe

area  bathrooms  y1  y2
0  2104.0        3.0   1   0
1  1600.0        3.0   1   0
2  2400.0        3.0   1   0
3  1416.0        2.0   0   1
4  3000.0        4.0   0   1
5  1985.0        4.0   1   0
6  1534.0        3.0   0   1
7  1427.0        3.0   1   0
8  1380.0        3.0   1   0
9  1494.0        3.0   1   0

In [11]:
#Step 3 - prepare data for tensorflow
#tensors are a generic version of vectors and matrices
#vector - is a list of numbers (1D tensor)
#matrix is a list of list of numbers (2d tensor)
#list of list of list of numbers (3D tensor)
#......
#convert features to input tensor
inputX = dataframe.loc[:, ['area', 'bathrooms']].as_matrix()
#convert labels to input tensors
inputY = dataframe.loc[:, ['y1', 'y2']].as_matrix()

In [12]:
inputX

array([[  2.10400000e+03,   3.00000000e+00],
       [  1.60000000e+03,   3.00000000e+00],
       [  2.40000000e+03,   3.00000000e+00],
       [  1.41600000e+03,   2.00000000e+00],
       [  3.00000000e+03,   4.00000000e+00],
       [  1.98500000e+03,   4.00000000e+00],
       [  1.53400000e+03,   3.00000000e+00],
       [  1.42700000e+03,   3.00000000e+00],
       [  1.38000000e+03,   3.00000000e+00],
       [  1.49400000e+03,   3.00000000e+00]])

In [13]:
inputY

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0]], dtype=int64)

In [14]:
#Step 4 - write out our hyperparameters
learning_rate = 0.000001
training_epochs = 2000
display_step = 50
n_samples = inputY.size

In [21]:
#Step 5 - Create our computation graph/neural network
#for feature input tensors, none means any numbers of examples,
#placeholders are gateways for data into our computation graph
x = tf.placeholder(tf.float32, [None,2])

#create weights
#2x2 float matrix, we'll keep updating through the
#training process
#variables in tf hold and update parameters
#in memory buffers containing tensors
W = tf.Variable(tf.zeros([2,2]))

#add biases (example is b in y = mx + b... b is the bias, like that)
b = tf.Variable(tf.zeros([2]))

#multiply our weights by our weights by our inputs, first calculation
#weights are how we govern how our data flows in our computation graph
#multiply inputs by weights and add biases
y_values = tf.add(tf.matmul(x, W), b)

#apply softmax to value we just created
#softmax is our activation function
y = tf.nn.softmax(y_values)

#Feed in a matrix of labels
y_ = tf.placeholder(tf.float32, [None, 2])

In [22]:
#Step 6 - perform training
#create our cost function, mean squared error
#reduce sum computes the sum of elements across dimensions of a tensor
cost = tf.reduce_sum(tf.pow(y_ - y, 2))/(2*n_samples)
#Gradient descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [24]:
#initialize variables and tensorflow session
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [36]:
#training loop
for i in range(training_epochs):
    sess.run(optimizer, feed_dict={x: inputX, y_: inputY})
    
    #write out logs of training
    if (i) % display_step == 0:
        cc = sess.run(cost, feed_dict={x: inputX, y_: inputY})
        print ("Training step:", '%04d' % (i), "cost=", "{:.9f}".format(cc)) #, \"W=", sess.run(W), "b=", sess.run(b))

print ("Optimization Finished!")
training_cost = sess.run(cost, feed_dict={x: inputX, y_: inputY})
print ("Training cost=", training_cost, "W=", sess.run(W), "b=", sess.run(b), '\n')
        

Training step: 0000 cost= 0.109531835
Training step: 0050 cost= 0.109531760
Training step: 0100 cost= 0.109531686
Training step: 0150 cost= 0.109531619
Training step: 0200 cost= 0.109531544
Training step: 0250 cost= 0.109531477
Training step: 0300 cost= 0.109531403
Training step: 0350 cost= 0.109531328
Training step: 0400 cost= 0.109531268
Training step: 0450 cost= 0.109531209
Training step: 0500 cost= 0.109531142
Training step: 0550 cost= 0.109531067
Training step: 0600 cost= 0.109531000
Training step: 0650 cost= 0.109530941
Training step: 0700 cost= 0.109530881
Training step: 0750 cost= 0.109530807
Training step: 0800 cost= 0.109530732
Training step: 0850 cost= 0.109530665
Training step: 0900 cost= 0.109530590
Training step: 0950 cost= 0.109530523
Training step: 1000 cost= 0.109530449
Training step: 1050 cost= 0.109530404
Training step: 1100 cost= 0.109530315
Training step: 1150 cost= 0.109530255
Training step: 1200 cost= 0.109530188
Training step: 1250 cost= 0.109530114
Training ste

In [37]:
sess.run(y, feed_dict = {x: inputX})

array([[ 0.71118802,  0.28881195],
       [ 0.66498947,  0.3350105 ],
       [ 0.73648036,  0.26351961],
       [ 0.64714378,  0.35285616],
       [ 0.78326094,  0.21673906],
       [ 0.70070869,  0.29929134],
       [ 0.65867209,  0.34132788],
       [ 0.64831036,  0.35168964],
       [ 0.64371371,  0.35628632],
       [ 0.65481567,  0.34518436]], dtype=float32)

In [38]:
#It's saying all houses are a good buy... which is wrong, only 7/10 were a good buy
#how to improve? add a hidden layer